# Generated by Django 4.2.5 on 2024-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='hammy_racing_games_won',
            new_name='hammy_stop_score',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='hammy_racing_time',
            field=models.FloatField(default=0.0),
        ),
    ]
